---
- name: Add deadsnakes ppa
  apt_repository:
    repo: 'ppa:deadsnakes/ppa'

- name: Install python pre-cursor packages
  apt:
    name: "{{ precursor_packages }}"
    update_cache: true
  vars:
    precursor_packages:
      - build-essential
      - libpq-dev
      - libssl-dev
      - openssl
      - libffi-dev
      - zlib1g-dev

- name: Install pip and python-dev packages
  apt:
    name: "{{ pip_packages }}"
  vars:
    pip_packages:
      - python3-pip
      - python3.7-dev

- name: Install python
  apt:
    name: python3.7