---
- hosts: all
  become: yes
  gather_facts: yes

  vars:
    python_versions: [2.7, 3.7]

  roles:
    - geerlingguy.nfs
    - geerlingguy.docker
    - Stouts.python

  tasks:
    - name: Install some helpful utilities.
      apt:
        name:
          - git
          - wget
          - curl
          - vim
        state: installed
    - name: Install Docker Compose pip library
      pip:
        name: docker-compose
        executable: pip-3.7